//logical and or operators using && 
console.log(4>2 && 3<8);
console.log(6<8 && 22>14);
console.log(15<7 && 7<7);
// using || 
console.log(4>2||8<2);
console.log(9<9||7>8);
console.log(null||0||undefined);
// bitwise (& or ^)
console.log(3|7);
console.log(5|9);
console.log(3&5);
console.log(6&6);
console.log(4>2||7>7||8>9 && 5>8 && 9<4);
//ternary
console.log((55>90)?"pass":"fail");
console.log((80<90)?"pass":"fail");
//relation 
let a=30;
let b=50;
console.log(a>b);
console.log(a<b);
console.log(a==b);
console.log(a!=b);
console.log(a===b);
console.log(a>=b);
console.log(a<=b);
//arithemtic
let a1=45;
let b1=90;
console.log(a1+b1);
console.log(a1-b1);
console.log(a1*b1);
console.log(a1/b1);
console.log(a1%b1);
